### ISSUE TITLE
Frontend master issue

### ISSUE THREAD

**Issue by MichaelPesce** [CATALOG-Historic-Records/orphaned-wells-ui#4]
- [x] Set up frontend framework with react
   - #2 
- [x] Create workflow for creating new projects, records
   - #3 
- [x] Add functionality for uploading individual document files
   - #3 
- [x] Create functionality for editing an uploaded record
   - #5 
- [ ] Add functionality for uploading multiple documents (.zip?)
- [x] Add error component for error handling
- [x] Set up authentication
   - we can use Google authentication for this
   - #6 
- [x] Deploy frontend
   - we can use Google storage bucket for this
